---
#- name: install ntp 
#  apt: pkg=ntp
#      state=present
#
#- name: Use Ubuntu's local ntp server as a fallback.
#  lineinfile: dest=/etc/ntp.conf
#              regexp="^server+[\s]+[a-z.]+"
#              line='server {{ NTP_SERVER }}'
#              backrefs=yes
#
#- name: start ntp serverice
#  service: name=ntp
#  	       state=present
#
#- name: install python-mysqldb 
#  apt: pkg=python-mysqldb 
#       state=present

- name: copy sysctl.conf
  template: src=sysctl.conf
            dest=/etc/
            state=present

- name: make sure sysctl.conf effective
  command: sysctl -p 

- name: install networking components
  apt: pkg={{ item }}
       state=present
  with_items:
   - neutron-plugin-ml2
   - neutron-plugin-openvswitch-agent
   - openvswitch-datapath-dkms
   - neutron-l3-agent
   - neutron-dhcp-agent

- name: copy files 
  file: src={{ item.name }}
        dest=/etc/{{ item.dest }}
        state=file
  with_items:
   - { name: 'dhcp_agent.ini', dest: 'neutron' }
   - { name: 'l3_agent.ini', dest: 'neutron' }

- name: copy metadata and ml2_conf.ini agent  
  template: src={{ item }}
            dest=/etc/neutron
  with_items:
   - metadata_agent.ini
   - ml2_conf.ini

- name: restart openvswitch-switch 
  service: name=openvswitch-switch
           state=restarted

- name: copy neutron.sh 
  file: src=neutron.sh
        dest=/root

- name: restart  neutron serverices
  service: name={{ item }}
           state=restarted
  with_items:
   - neutron-plugin-openvswitch-agent
   - neutron-l3-agent
   - neutron-dhcp-agent
   - neutron-metadata-agent
