---
- name: install ntp 
  apt: pkg=ntp
      state=present

- name: Use Ubuntu's local ntp server as a fallback.
  lineinfile: dest=/etc/ntp.conf
              regexp="^server+[\s]+[a-z.]+"
              line='server {{ NTP_SERVER }}'
              backrefs=yes

- name: start ntp serverice
  service: name=ntp
  	       state=present

- name: install python-mysqldb 
  apt: pkg=python-mysqldb 
       state=present


